/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package statkiklient;

/**
 *
 * @author Lenovo
 */
public class GlowneOkienko extends javax.swing.JFrame {

    /**
     * Creates new form GlowneOkienko
     */
    public GlowneOkienko() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitShipButton = new javax.swing.JButton();
        submitPortButton = new javax.swing.JButton();
        submitShipPositionButton = new javax.swing.JButton();
        pobierzDaneStatkuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        submitShipButton.setText("Zgłoś statek");
        submitShipButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitShipButtonMouseClicked(evt);
            }
        });
        submitShipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitShipButtonActionPerformed(evt);
            }
        });

        submitPortButton.setText("Zgłoś Port");
        submitPortButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitPortButtonMouseClicked(evt);
            }
        });

        submitShipPositionButton.setText("Zgłoś pozycję statku");
        submitShipPositionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitShipPositionButtonMouseClicked(evt);
            }
        });
        submitShipPositionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitShipPositionButtonActionPerformed(evt);
            }
        });

        pobierzDaneStatkuButton.setText("Pobierz dane statku");
        pobierzDaneStatkuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pobierzDaneStatkuButtonMouseClicked(evt);
            }
        });
        pobierzDaneStatkuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobierzDaneStatkuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitShipButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pobierzDaneStatkuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitPortButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitShipPositionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(submitShipButton)
                .addGap(31, 31, 31)
                .addComponent(pobierzDaneStatkuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(submitPortButton)
                .addGap(32, 32, 32)
                .addComponent(submitShipPositionButton)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitShipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitShipButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitShipButtonActionPerformed

    private void submitShipPositionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitShipPositionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitShipPositionButtonActionPerformed

    private void submitShipButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitShipButtonMouseClicked
        ZglaszanieStatkuOkienko dodajStatek = new ZglaszanieStatkuOkienko();
        dodajStatek.setVisible(true);
    }//GEN-LAST:event_submitShipButtonMouseClicked

    private void submitPortButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitPortButtonMouseClicked
        ZglaszaniePortuOkienko dodajPort = new ZglaszaniePortuOkienko();
        dodajPort.setVisible(true);
    }//GEN-LAST:event_submitPortButtonMouseClicked

    private void submitShipPositionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitShipPositionButtonMouseClicked
        ZglaszaniePozycjiStatkuOkienko podajPozycje = new ZglaszaniePozycjiStatkuOkienko();
        podajPozycje.setVisible(true);
    }//GEN-LAST:event_submitShipPositionButtonMouseClicked

    private void pobierzDaneStatkuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobierzDaneStatkuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pobierzDaneStatkuButtonActionPerformed

    private void pobierzDaneStatkuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pobierzDaneStatkuButtonMouseClicked
        WyswietlanieDanychStatkuOkienko pobierzStatek = new WyswietlanieDanychStatkuOkienko();
        pobierzStatek.setVisible(true);
    }//GEN-LAST:event_pobierzDaneStatkuButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlowneOkienko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlowneOkienko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlowneOkienko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlowneOkienko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlowneOkienko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pobierzDaneStatkuButton;
    private javax.swing.JButton submitPortButton;
    private javax.swing.JButton submitShipButton;
    private javax.swing.JButton submitShipPositionButton;
    // End of variables declaration//GEN-END:variables
}
